### ISSUE TITLE
SSL verification error

### ISSUE THREAD

**Issue by hassan-crewlogix** [consolibyte/quickbooks-php#153]
i am getting SSL verification error . i dont have SSL on my server .
i have searched for this and came up to the solution to add this line in HTTP.php 

`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`

there is no way i can disable ssl veryfy peer using my env file .

**Comment by consolibyte** [comment]
By disabling SSL verification, you are opening up a GIGANTIC security hole in your application. You also do not conform to Intuit's requirements for developing QuickBooks-integrated applications. 

Fix your server so that it validates SSL certificates correctly, and this problem will go away. This is not a problem that should be fixed in code. Fix your server configuration.

**Comment by hassan-crewlogix** [comment]
thanks for replying

**Comment by hassan-crewlogix** [comment]
It would be great if you provide option for disabling SSL verification from env or config file . 
Let the user worry about securyity .
