### ISSUE TITLE
mobile, isEcommerce required - MerchantService.php QuickBooks_MerchantService 

### ISSUE THREAD

**Issue by kimwue** [consolibyte/quickbooks-php#197]
As per emails from Intuit Developer, mobile and isEcommerce (contained in context) will be required, on February 1, 2018.

How should we provide those information using MerchantService.php->authorize() ?

Thanks.

**Comment by amandato** [comment]
For those scrambling for a fix, we discovered the best place to put these 2 tags is within the QuickBooks\MerchantService.php file, in the protected function _createCreditCardXML().  Inside the "if ($include_amounts) {" section, add the following in this order before the <Amount> tag is added to the $xml variable:

```
$xml .= '			<IsECommerce>true</IsECommerce>' . QUICKBOOKS_CRLF;
$xml .= '			<IsMobile>false</IsMobile>' . QUICKBOOKS_CRLF;
```

Note this needs to be above the <Amount> tag. 

This whole thing is beyond frustrating. The fact these new tags are now required blows my mind. The emails they have sent never expressed the urgency of the matter, "oh your application may be affected if". Aree they not logging our API requests? They should see who is not passing these arguments in their API calls today to know who to contact with the heading "February first your application will break unless you update it". More frustrating is that this is required, which to me seems like someone in upper management wants a better report which is what is driving this NOT backwards compatible API decision. Unfortunately the opposite should be true, someone at Intuit needs to stand up and say "API developers, do not do anything that could lead to loss in transactions" which would put a huge value on backwards compatibility in order to maximize sales. PayPal has APIs that haven't changed since the early 2000's. They do this because the last thing they want is to have a decline in transactions because they can't get everyone using their updated APIs. What makes this worse there is no clear documentation on what isMobile or IsECommerce means or that they must be in a particular order in the XML. Their first examples they published had camel case typos indicating to me that they never tested what they used as an example. It is obvious to me that processing credit card transactions is not a primary goal of Intuit Exceedingly frustrating.

**Comment by kimwue** [comment]
@amandato 
Thanks for your info, I forked and updated to generate the correct xml. I created a pull request. Feel free to use my fork until its merged.
