### ISSUE TITLE
Queued Data Getting Duplicated

### ISSUE THREAD

**Issue by clrncmcnlsn** [consolibyte/quickbooks-php#254]
The code below successfully queues `customers` to the `quickbooks_queue` table and prevents the same `customers` from being re-queued whenever another `syncing` event occurs.
```php
$sold_items = mysqli_query($link, 'select * from sales where qty_sold != 0');

foreach($sold_items as $sold_item)
{
    $duplicate = mysqli_query($link, 'select * from quickbooks_queue where qb_action == "CustomerAdd" and ident == '.$sold_item['customer_id']);

    if(!$duplicate)
    {
        $Queue->enqueue(QUICKBOOKS_ADD_CUSTOMER, $customer['customer_id']);
    }
}

```
The problem is that once a customer gets `synced` with `QuickBooks Desktop` and its status becomes <kbd>s</kbd> in the `quickbooks_queue` table,
```php
$Queue->enqueue(QUICKBOOKS_ADD_CUSTOMER, $customer['customer_id']);
```
adds the same customer to the queue, skipping the duplicate logic.

This is a huge problem with our `invoices`

**Comment by consolibyte** [comment]
This is expected behavior. If you tell it to add a customer twice, it will attempt to add a customer twice. 

The correct pattern to follow here is to store the ListID you get back once you create a customer (or the TxnID once you create an invoice). 

Then, based on the presence/absence of a ListID/TxnID, you know whether to add the customer/invoice again or not (or whether to do a MOD vs. an ADD).
