### ISSUE TITLE
Fatal error when using OAuth2

### ISSUE THREAD

**Issue by aik099** [consolibyte/quickbooks-php#269]
When OAuth2 support was implemented existing methods were renamed to have "V1" suffix and new methods with "V2" suffix were added.

Unfortunately not all places, where old method names were used were updated.

For `QuickBooks_IPP_IntuitAnywhere` PHP class:

* `oauthLoad` method was renamed into `oauthLoadV1`
* method use was replaced in `load` method
* method use wasn't replaced in `expiry`, `reconnect` and `disconnect` methods

**Comment by ve7tcc** [comment]
Is it an easy fix?

**Comment by aik099** [comment]
It looks like it (probably changes in original PR, where oAuth2 was added can be adapted to forgotten 3 methods), but I don't know much about oAuth2 to be certain.

It's better for original PR author (@ebogdanov) to make/test a fix.

**Comment by ebogdanov** [comment]
@aik099 Well, as I understand problem is not with my branch, but with master. 
And this is not my implementation of OAuth2. My PR was based on classes, not method renames and it was was open for 1 year without review/comments from repo's owner. 
When Intuit anounced migration guide to v2 own version was implemented, without any comments about such decision rather than use/improve mine.

I can try fix your issue, but I've some feeling that due some unnamed policy it will not be merged. :)

**Comment by aik099** [comment]
> When Intuit anounced migration guide to v2 own version was implemented, without any comments about such decision rather than use/improve mine.

@ebogdanov , that was unexpected. 

> I can try fix your issue, but I've some feeling that due some unnamed policy it will not be merged. :)

The smaller PRs tend to be merged faster. If you have time, please see if you can fix 3 methods with issues. Alternatively I'll wait for @consolibyte response/release.

My workflow is as follows: instead of doing connect via UI when expired token is discovered I prefer to reconnect every time so that current token lifetime is extended (or something like that) to allow non-UI workflows (e.g. sending data to QuickBooks from CLI via CRON).

**Comment by ebogdanov** [comment]
reconnect means "refresh"?

**Comment by aik099** [comment]
> reconnect means "refresh"?

That means I call `reconnect` method literarily and it causes Fatal Error to happen.

**Comment by ebogdanov** [comment]
OK, got it. I will try to my best and solve this on this weekend.

**Comment by ebogdanov** [comment]
> > reconnect means "refresh"?
> 
> That means I call `reconnect` method literarily and it causes Fatal Error to happen.
@aik099 

OK, I've researched code. 
Yes, there is a bug with method rename, but seems it will be left untouched for history, since in new conditions this code should never be executed.

By new QuickBooks_IPP_IntuitAnywhere design you should not call methods you've mentioned in case of OAuth2 usage. Them are only for OAuth1, and it is obsolete now.

In case of OAuth2 Refresh token is done automatically before every API method call if TTL of access token value is less than 60 seconds. (see quickbooks-php/QuickBooks/IPP.php, function IDS). So that you should not worry about refreshed and can just call methods, like there is no any access/refresh token doubts and rules. 

Problem in this case can be only if you're running this code in multithreading, and concurent threads will try to load new token, but for 95% of PHP scripts this will never happen. For other 5% - they will find how to deal with this, or already migrated to original Intuit's SDK.

**Comment by aik099** [comment]
> Yes, there is a bug with method rename, but seems it will be left untouched for history, since in new conditions this code should never be executed.

Library supports both oAuth1 and oAuth2, so both should work. There is no way extend lifetime of `oAuth1` token except for calling `reconnect` method, which is now broken.

> In case of OAuth2 Refresh token is done automatically before every API method call if TTL of access token value is less than 60 seconds. (see quickbooks-php/QuickBooks/IPP.php, function IDS). So that you should not worry about refreshed and can just call methods, like there is no any access/refresh token doubts and rules.

That is surely inconsistent behavior. For oAuth1 we have non-working `reconnect` method now and instead of updating `reconnect` method for oAuth2 support new `\QuickBooks_IPP::_handleRenewal` method is introduced, that is called from `\QuickBooks_IPP::IDS` method you've mentioned.

I'm proposing these steps:

1. inside `reconnect` method throw an exception, when used with oAuth2
2. update `reconnect` method to call "...v1" method to avoid fatal error

**Comment by aik099** [comment]
@ebogdanov , I haven't found any exceptions being thrown in the library (I guess errors are reported by other means). That's why I've created #271 that at least solves Fatal Error issues for oAuth1 calls.

**Comment by ve7tcc** [comment]
So with the code now I don't have to call $IntuitAnywhere->expiry to check if it needs a refresh?

How can I do a disconnect?
$IntuitAnywhere->disconnect($the_username, $the_tenant) still has a username parameter.

Thanks!

**Comment by ve7tcc** [comment]
I added pr #273 to create a $IntuitAnywhere->disconnectV2($the_tenant)
So ignore my previous comment.
