### ISSUE TITLE
quickbooks-php not sending data service items all fields in quickbook 2011 desktop 

### ISSUE THREAD

**Issue by yasharma** [consolibyte/quickbooks-php#64]
we are able to connect a quickbooks-php api with quickbook pro and can send data in items (Non-Inventory) in fields name and types only, however their are other fields description, quantity and customer jobs where we are trying to send data but getting error. please see the attached screenshot regarding the error. please suggest how to fix this.
![screenshot-europa promaticstechnologies com 2015-02-25 10-56-04](https://cloud.githubusercontent.com/assets/3693571/6365798/fb419eee-bce2-11e4-81e4-27bc482eed8c.png)

**Comment by consolibyte** [comment]
Please post code to reproduce this, so that we can help you resolve this. 

Or at the very least, post the XML being sent to Intuit ($Service->lastRequest($Context)) and the XML you received ($Service->lastResponse($Context)). 

Unfortuantely, what you posted above is not helpful because:
a) it's an image, and I can't copy/paste from it to make it readable
b) it seems like it's a screenshot from within your browser, which means your browser stripped all the XML tags out when it rendered it
